// File generated by the BNF Converter (bnfc 2.9.6.2).

module.exports = grammar({
  name: 'BasilIR',
  extras: $ =>[
    /\s/,
    /\/\*[^*]*\*([^\*\/][^*]*\*|\*)*\//,
    /\/\/.*/,
  ],
  rules: {
    Module: $ =>
      $.list_Decl,
    list_Decl: $ =>
      repeat1(seq($.Decl,";")),
    list_token_BlockIdent: $ =>
      seq($.token_BlockIdent,repeat(seq(",",$.token_BlockIdent))),
    Semicolons: $ =>
      choice(
        choice(),
        seq(optional($.Semicolons),";")
      ),
    Decl: $ =>
      choice(
        seq("axiom",optional($.AttribSet),$.Expr),
        seq("memory","shared",$.token_GlobalIdent,":",$.Type),
        seq("memory",$.token_GlobalIdent,":",$.Type),
        seq("var",$.token_GlobalIdent,":",$.Type),
        seq("declare-fun",optional($.AttribSet),$.token_GlobalIdent,":","(",optional($.list_Type),")","->",$.Type),
        seq("define-fun",optional($.AttribSet),$.token_GlobalIdent,"(",optional($.list_Params),")","->",$.Type,"=",$.Expr),
        seq("prog","entry",$.token_ProcIdent,optional($.AttribSet)),
        seq("prog","entry",$.token_ProcIdent,optional($.AttribSet),$.token_BeginList,optional($.list_ProgSpec),$.token_EndList),
        seq("proc",$.token_ProcIdent,"(",optional($.list_Params),")","->","(",optional($.list_Params),")",optional($.AttribSet),optional($.list_FunSpec),optional($.ProcDef))
      ),
    list_Type: $ =>
      seq($.Type,repeat(seq(",",$.Type))),
    ProcDef: $ =>
      choice(
        choice(),
        seq($.token_BeginList,optional($.list_Block),$.token_EndList)
      ),
    IntType: $ =>
      $.token_INTTYPE,
    BoolType: $ =>
      $.token_BOOLTYPE,
    MapType: $ =>
      seq("(",$.Type,"->",$.Type,")"),
    BVType: $ =>
      $.token_BVTYPE,
    Type: $ =>
      choice(
        $.IntType,
        $.BoolType,
        $.MapType,
        $.BVType
      ),
    list_Expr: $ =>
      seq($.Expr,repeat(seq(",",$.Expr))),
    IntVal: $ =>
      choice(
        $.token_IntegerHex,
        $.token_IntegerDec
      ),
    BVVal: $ =>
      seq($.IntVal,":",$.BVType),
    Endian: $ =>
      choice(
        "le",
        "be"
      ),
    Assignment: $ =>
      seq($.LVar,":=",$.Expr),
    Stmt: $ =>
      choice(
        "nop",
        $.Assignment,
        seq("(",$.list_Assignment,")"),
        seq($.LVar,":=","load",$.Endian,$.token_GlobalIdent,$.Expr,$.IntVal),
        seq("store",$.Endian,$.token_GlobalIdent,$.Expr,$.Expr,$.IntVal),
        seq($.LVar,":=","load",$.Endian,$.Var,$.Expr,$.IntVal),
        seq($.LVar,":=","store",$.Endian,$.Var,$.Expr,$.Expr,$.IntVal),
        seq(optional($.LVars),"call",$.token_ProcIdent,"(",optional($.CallParams),")"),
        seq("indirect","call",$.Expr),
        seq("assume",$.Expr),
        seq("guard",$.Expr),
        seq("assert",$.Expr)
      ),
    list_Assignment: $ =>
      seq($.Assignment,repeat(seq(",",$.Assignment))),
    LocalVar: $ =>
      seq($.token_LocalIdent,":",$.Type),
    GlobalVar: $ =>
      seq($.token_GlobalIdent,":",$.Type),
    list_LocalVar: $ =>
      seq($.LocalVar,repeat(seq(",",$.LocalVar))),
    Var: $ =>
      choice(
        $.LocalVar,
        $.GlobalVar
      ),
    NamedCallReturn: $ =>
      seq($.LVar,"=",$.token_LocalIdent),
    list_NamedCallReturn: $ =>
      seq($.NamedCallReturn,repeat(seq(",",$.NamedCallReturn))),
    LVars: $ =>
      choice(
        choice(),
        seq("var","(",$.list_LocalVar,")",":="),
        seq("(",$.list_LVar,")",":="),
        seq("(",optional($.list_NamedCallReturn),")",":=")
      ),
    NamedCallArg: $ =>
      seq($.token_LocalIdent,"=",$.Expr),
    list_NamedCallArg: $ =>
      seq($.NamedCallArg,repeat(seq(",",$.NamedCallArg))),
    CallParams: $ =>
      choice(
        $.list_Expr,
        $.list_NamedCallArg
      ),
    Jump: $ =>
      choice(
        seq("goto","(",optional($.list_token_BlockIdent),")"),
        "unreachable",
        seq("return","(",optional($.list_Expr),")"),
        "return"
      ),
    LVar: $ =>
      choice(
        seq("var",$.LocalVar),
        $.GlobalVar
      ),
    list_LVar: $ =>
      seq($.LVar,repeat(seq(",",$.LVar))),
    list_Block: $ =>
      seq($.Block,repeat(seq(";",$.Block))),
    StmtWithAttrib: $ =>
      seq($.Stmt,optional($.AttribSet)),
    list_StmtWithAttrib: $ =>
      repeat1(seq($.StmtWithAttrib,";")),
    JumpWithAttrib: $ =>
      seq($.Jump,optional($.AttribSet)),
    PhiExpr: $ =>
      seq($.token_BlockIdent,"->",$.Var),
    list_PhiExpr: $ =>
      seq($.PhiExpr,repeat(seq(",",$.PhiExpr))),
    PhiAssign: $ =>
      seq($.LVar,":=","phi","(",optional($.list_PhiExpr),")"),
    list_PhiAssign: $ =>
      seq($.PhiAssign,repeat(seq(",",$.PhiAssign))),
    Block: $ =>
      choice(
        seq("block",$.token_BlockIdent,optional($.AttribSet),$.token_BeginList,optional($.list_StmtWithAttrib),$.JumpWithAttrib,";",$.token_EndList),
        seq("block",$.token_BlockIdent,optional($.AttribSet),$.token_BeginList,"(",optional($.list_PhiAssign),")",";",optional($.list_StmtWithAttrib),$.JumpWithAttrib,";",$.token_EndList)
      ),
    AttrKeyValue: $ =>
      seq($.token_BIdent,"=",$.Attr),
    list_AttrKeyValue: $ =>
      seq($.AttrKeyValue,repeat(seq(";",$.AttrKeyValue))),
    AttribSet: $ =>
      choice(
        seq($.token_BeginRec,optional($.list_AttrKeyValue),optional($.Semicolons),$.token_EndRec),
        choice()
      ),
    list_Attr: $ =>
      seq($.Attr,repeat(seq(";",$.Attr))),
    Attr: $ =>
      choice(
        seq($.token_BeginRec,optional($.list_AttrKeyValue),optional($.Semicolons),$.token_EndRec),
        seq($.token_BeginList,optional($.list_Attr),$.token_EndList),
        $.Value,
        $.token_Str
      ),
    Params: $ =>
      seq($.token_LocalIdent,":",$.Type),
    list_Params: $ =>
      seq($.Params,repeat(seq(",",$.Params))),
    Value: $ =>
      choice(
        $.BVVal,
        $.IntVal,
        "true",
        "false"
      ),
    Expr: $ =>
      choice(
        $.Value,
        $.LocalVar,
        $.GlobalVar,
        seq("forall",$.LambdaDef),
        seq("exists",$.LambdaDef),
        seq("old","(",$.Expr,")"),
        seq($.token_GlobalIdent,"(",optional($.list_Expr),")"),
        seq($.BinOp,"(",$.Expr,",",$.Expr,")"),
        seq($.BoolBinOp,"(",optional($.list_Expr),")"),
        seq($.UnOp,"(",$.Expr,")"),
        seq("zero_extend","(",$.IntVal,",",$.Expr,")"),
        seq("sign_extend","(",$.IntVal,",",$.Expr,")"),
        seq("extract","(",$.IntVal,",",$.IntVal,",",$.Expr,")"),
        seq("bvconcat","(",optional($.list_Expr),")")
      ),
    LambdaDef: $ =>
      seq("(",$.list_LocalVar,")",$.token_LambdaSep,$.Expr),
    BinOp: $ =>
      choice(
        $.BVBinOp,
        $.BVLogicalBinOp,
        $.IntLogicalBinOp,
        $.IntBinOp,
        $.EqOp
      ),
    UnOp: $ =>
      choice(
        $.BVUnOp,
        "boolnot",
        "intneg",
        "booltobv1"
      ),
    EqOp: $ =>
      choice(
        "eq",
        "neq"
      ),
    BVUnOp: $ =>
      choice(
        "bvnot",
        "bvneg"
      ),
    BVBinOp: $ =>
      choice(
        "bvand",
        "bvor",
        "bvadd",
        "bvmul",
        "bvudiv",
        "bvurem",
        "bvshl",
        "bvlshr",
        "bvnand",
        "bvnor",
        "bvxor",
        "bvxnor",
        "bvcomp",
        "bvsub",
        "bvsdiv",
        "bvsrem",
        "bvsmod",
        "bvashr"
      ),
    BVLogicalBinOp: $ =>
      choice(
        "bvule",
        "bvugt",
        "bvuge",
        "bvult",
        "bvslt",
        "bvsle",
        "bvsgt",
        "bvsge"
      ),
    IntBinOp: $ =>
      choice(
        "intadd",
        "intmul",
        "intsub",
        "intdiv",
        "intmod"
      ),
    IntLogicalBinOp: $ =>
      choice(
        "intlt",
        "intle",
        "intgt",
        "intge"
      ),
    BoolBinOp: $ =>
      choice(
        "booland",
        "boolor",
        "boolimplies"
      ),
    RequireTok: $ =>
      choice(
        "require",
        "requires"
      ),
    EnsureTok: $ =>
      choice(
        "ensure",
        "ensures"
      ),
    FunSpec: $ =>
      choice(
        seq($.RequireTok,$.Expr),
        seq($.EnsureTok,$.Expr),
        seq("invariant",$.token_BlockIdent,$.Expr)
      ),
    ProgSpec: $ =>
      choice(
        seq("rely",$.Expr),
        seq("guarantee",$.Expr)
      ),
    list_FunSpec: $ =>
      repeat1(seq($.FunSpec,";")),
    list_ProgSpec: $ =>
      repeat1(seq($.ProgSpec,";")),
    token_BVTYPE: $ =>
      /bv\d+/,
    token_INTTYPE: $ =>
      /int/,
    token_BOOLTYPE: $ =>
      /bool/,
    token_BIdent: $ =>
      /\.(_|[a-zA-Z])([#\$\._~]|(\d|[a-zA-Z]))*/,
    token_LocalIdent: $ =>
      /([#_]|[a-zA-Z])([#\$\._]|(\d|[a-zA-Z]))*/,
    token_GlobalIdent: $ =>
      /\$([#\$\._]|(\d|[a-zA-Z]))+/,
    token_BlockIdent: $ =>
      /%([#\$\._]|(\d|[a-zA-Z]))+/,
    token_ProcIdent: $ =>
      /@([#\$\._]|(\d|[a-zA-Z]))+/,
    token_BeginList: $ =>
      /\[/,
    token_EndList: $ =>
      /\]/,
    token_BeginRec: $ =>
      /\{/,
    token_EndRec: $ =>
      /\}/,
    token_LambdaSep: $ =>
      /::|->/,
    token_Str: $ =>
      /"([^"\\]|\\["\\fnrt])*"/,
    token_IntegerHex: $ =>
      /0x([abcdef]|\d)+/,
    token_IntegerDec: $ =>
      /\d+/,
  },
});
