// File generated by the BNF Converter (bnfc 2.9.6.2).

module.exports = grammar({
  name: 'list',
  rules: {
    Start: $ =>
      choice(
        seq("a",$.list_NETerm),
        seq("b",optional($.list_PETerm)),
        seq("c",optional($.list_PESep)),
        seq("d",$.list_NESep)
      ),
    NETerm: $ =>
      "a",
    list_NETerm: $ =>
      choice(
        seq($.NETerm,";"),
        seq($.NETerm,";",$.list_NETerm)
      ),
    PETerm: $ =>
      "b",
    list_PETerm: $ =>
      choice(
        choice(),
        seq($.PETerm,"|",optional($.list_PETerm))
      ),
    PESep: $ =>
      "c",
    list_PESep: $ =>
      choice(
        choice(),
        $.PESep,
        seq($.PESep,",",optional($.list_PESep))
      ),
    NESep: $ =>
      "d",
    list_NESep: $ =>
      choice(
        $.NESep,
        seq($.NESep,":",$.list_NESep)
      ),
  },
});
